# Use an official Node.js runtime as a parent image
FROM node:18-alpine

# Set the working directory to /app
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . ./

# Set environment variables
ENV PORT=3001

# Expose port 3000
EXPOSE 3001

# Start the development server with hot reloading
CMD ["npm", "run", "dev"]