version: "3.9"
services:
  api:
    build:
      context: ../api
      dockerfile: Dockerfile.api
    volumes:
      - ../api/src:/app/api/
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://ponder_user:postgres@inconsistent_db:5432/ponder
    ports:
      - "3000:3000"
    command: bun run bun:dev
  client:
    build:
      context: ../client
      dockerfile: Dockerfile.client
    ports:
      - "3001:3001"
    volumes:
      - ../client/src:/app/client/
      - /app/client/node_modules
    stdin_open: true
    tty: true
    command: npm run dev
  inconsistent_db:
    image: postgres:15
    container_name: inconsistent_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=ponder_user
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ponder
      - POSTGRES_PORT=5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
