FROM oven/bun 
# FROM jarredsumner/bun:edge
# Set the working directory to /app
WORKDIR /app

COPY package.json .
COPY bun.lockb bun.lockb

# Install dependencies
RUN bun install

# Copy the rest of the application code to the working directory
COPY . ./

# Start the development server with hot reloading
CMD ["bun","run", "bun:dev"]

