name: client_checks
on: push

jobs:
  type-check:
    name: Type Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./client"

    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: canary
      - run: bun install
      - run: bun run check:tsc

  lint-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./client"

    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: canary
      - run: bun install
      - run: bun run check:formatting

  build-check:
    name: Linting Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./client"

    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: canary
      - run: bun install
      - run: bun run check:linting
